### ISSUE TITLE
ShareIT: Comments

### ISSUE THREAD

**Issue by drkkjh** [drkkjh/Health-Wealth#45]
Username of the one commenting is same as user who posted the post/discussion

**Comment by drkkjh** [comment]
Fixed by passing current user's username into each PostCard and DiscussionCard respectively.

**Comment by ish1506** [comment]
This issue still exists when user comments through the comment icon (instead of the "view X comments" section)
